apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nkhu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0067-tenant/tkrw-pr712-0075-0067-app/devfile-sample-nkhu@sha256:162fe6ea7f66e0ebcc660487d670272bc6557412effc55ec5eed4d79aa38c872
        name: my-nodejs
        resources: {}
status: {}
